name: Build and push Docker images

on:
  workflow_dispatch:
  #schedule:
  # every monday at 2am
    #- cron: '0 1 * * 1'

jobs:
  java-minimal:
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: java-minimal
      context: java-minimal
      test: true
      base_image: base
      python_version_1: 3.10.9
      python_version_2: 3.9.16
      branch: ${{ github.ref }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
